### ISSUE TITLE
[Announcement] 0.5.0-beta.3 published

### ISSUE THREAD

**Issue by amis92** [amis92/RecordGenerator#100]
The beta version is available on NuGet.org and includes all the good stuff we've worked on recently! See https://github.com/amis92/RecordGenerator/milestone/9?closed=1

https://www.nuget.org/packages/Amadevus.RecordGenerator/0.5.0-beta.3

**Comment by amis92** [comment]
@atifaziz @jflepp @megakid Thanks for contributions! Sorry it took so long to publish 😅

**Comment by bboyle1234** [comment]
This is awesome work. Thank you very much.

**Comment by amis92** [comment]
There's a newer preview.1 released, closing this issue.

https://github.com/amis92/RecordGenerator/releases/tag/v0.5.0-preview.1
