### ISSUE TITLE
.NET 4.0 Support for version 0.5

### ISSUE THREAD

**Issue by wischi-chr** [amis92/RecordGenerator#107]
At the moment I'm using version 0.4.1 on .net 4.0 (sadly I have to support that version for a customer with windows XP 😭 )

I tried to update to 0.5-beta but sadly it no longer works (I think because the target is now netstandard 1.0 and .net40 doesn't implement that standard)

Is it possible to add .net40 as a target framework (I guess only the attribute assembly needs to support that) or do you think net40 is to old to support it?

Thanks in advance.

**Comment by amis92** [comment]
I *think* this shouldn't be a problem in terms of just the attributes. I'll add this to the 0.5 backlog.
