### ISSUE TITLE
Doesn't work properly with SignalR

### ISSUE THREAD

**Issue by DmitriyBobrovskiy** [amis92/RecordGenerator#143]
If I try to call from frontend side some SignalR method which takes type marked as `[Record]` then frontend can't call this method and shows next error:
```
logging.service.ts:114 Error: Failed to invoke 'addrecipe' due to an error on the server.  
InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
    at _this.callbacks.<computed> (HubConnection.js:248)
    at HubConnection.push../node_modules/@aspnet/signalr/dist/esm/HubConnection.js.HubConnection.processIncomingData (HubConnection.js:342)
    at WebSocketTransport.HubConnection.connection.onreceive (HubConnection.js:65)
    at WebSocket.webSocket.onmessage [as __zone_symbol__ON_PROPERTYmessage] (WebSocketTransport.js:107)
    at WebSocket.wrapFn (zone-evergreen.js:1218)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41645)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
```

And if I add `{ set; }` to the class' properties then it's working.

Is there any workaround/working solution or I should stop using this library and wait for .NET 5?
Thank you!

**Comment by DmitriyBobrovskiy** [comment]
Okay, I have found some workaround. At least it's working.
My SignalR method's signature was:
```csharp
public Recipe AddRecipe(RecipeRequest request)
{
    // some logic...
}
```
And I changed to:
```csharp
public Recipe AddRecipe(RecipeRequest.Builder requestBuilder)
{
    var request = requestBuilder.ToImmutable();
    // some logic...
}
```

If anybody can suggest something better, please, go ahead.

**Comment by amis92** [comment]
Generally yes, this is very much deprecated in favor of C#9 records.

But your workaround is also okay. I used the same approach for using RecordGenerator with XML serialization.

**Comment by DmitriyBobrovskiy** [comment]
Found another one problem related to this.
Just in case if anybody in future will be interested in this.
If you get from parameter any `[Record]` type that consists from other `[Record]` types then the problem is the same.
I solved it the next way:
Original:
```csharp
public Corners MarkCorners(Corners corners)
{
    // some logic
}
```
After fix:
```csharp
public Corners MarkCorners(CornersRequest cornersRequest)
{
    var corners = cornersRequest.ToCorners();
    // other logic
}
```
And `CornersRequest` is:
```csharp
public class CornersRequest
{
    public Point.Builder TopLeft { get; set; }
    public Point.Builder BottomRight { get; set; }

    public Corners ToCorners() =>
        new Corners(TopLeft.ToImmutable(), BottomRight.ToImmutable());
}
```

**Comment by amis92** [comment]
Yes. You'll find C#9 record to work perfectly without all these workarounds :) I'm already using them and it's so much better than this... :D

**Comment by DmitriyBobrovskiy** [comment]
Yeah, but you know, it's quite early to use it in production :)
