### ISSUE TITLE
Analyzer rules help Uri appears to be broken

### ISSUE THREAD

**Issue by mwpowellhtx** [amis92/RecordGenerator#34]
[Anything special about that](http://github.com/amis92/RecordGenerator/blob/master/src/Amadevus.RecordGenerator.Analyzers/Descriptors.cs#L15), or it just need to inform some sort of documentation, wiki, or other, behind it?

Thanks!

**Comment by amis92** [comment]
Well, I mean, the link is valid and builds correctly (given rule suffix), see https://amis92.github.io/RecordGenerator/analyzers/rules/RecordGen1000.html

But clicking `See help` in Visual Studio when browsing Analyzer's Rules doesn't navigate to this URL, and I believe it does so for xUnit's Analyzers. I don't know what else has to be done to duplicate that behavior.

**Comment by mwpowellhtx** [comment]
Oh, duh; yes, of course. :+1: The base address was just the prefix. I see that now, of course. Thanks!
