### ISSUE TITLE
Necessity of starting from Analyzer project template?

### ISSUE THREAD

**Issue by mwpowellhtx** [amis92/RecordGenerator#36]
You must have [started from an Analyzer project template](/amis92/RecordGenerator/blob/master/src/Amadevus.RecordGenerator.Analyzers/Resources.Designer.cs), because there appear to be some unused resource properties, i.e. [AnalyzerMessageFormat](/amis92/RecordGenerator/blob/master/src/Amadevus.RecordGenerator.Analyzers/Resources.Designer.cs#L87)?

Q: Is it necessary to start from that project template?
Q: and/or, I am not specifying any resource properties or anything like that.

I can't find a reason to define them, but was wondering if it was at all necessary... Thanks!

**Comment by mwpowellhtx** [comment]
Understood.

I guess what I'm asking is, did you start from an *"Analyzers"* (or other) project template, or was it just your run of the mill ``.NET Standard Class Library``?

**Comment by amis92** [comment]
Oh, yeah, the Analyzer + its VSIX project and Analyzers.Tests are from `Roslyn Analyzer + CodeFix` template which I think is installed with Roslyn SDK extension.

**Comment by mwpowellhtx** [comment]
For the [VSIX](/amis92/RecordGenerator/tree/master/src/Amadevus.RecordGenerator.Analyzers.Vsix), yes, of course. But, for the [Analyzers](/amis92/RecordGenerator/tree/master/src/Amadevus.RecordGenerator.Analyzers) themselves? Sorry to split hairs...

**Comment by amis92** [comment]
Yeah, these three projects (Analyzers, Vsix, Analyzers.Tests) are all generated from single template from Roslyn SDK :)
