### ISSUE TITLE
What's the difference between the Generator internal bits

### ISSUE THREAD

**Issue by mwpowellhtx** [amis92/RecordGenerator#37]
This is where our paths fork a little bit. But, I was curious what the internal bits are doing as far as *Record Generators* are concerned? Just in understanding what is being generated from an analytical perspective, from ``RecordGenerator``, etc. Specifically, what is ``RecordPartialGenerator``, ``BuilderPartialGenerator``, and ``DeconstructPartialGenerator``? This appears to be the rub of what ``RecordGenerator`` is doing as a whole. Thanks!

**Comment by amis92** [comment]
Well,
* `RecordGenerator` just calls three other "partial" generators. The result is returned as a list of members to write for given [Record]-decorated class; each of those generated a single `partial` class with appropriate contents.
* `RecordPartialGenerator` is responsible for generating a partial class with constructor, `With`-methods and `Update` method.
* `BuilderPartialGenerator` creates partial class with `Builder` subclass that is a mutable copy of the parent class and has mapping methods.
* `DeconstructPartialGenerator` provides partial class with a single method `Deconstruct` that makes it possible in C#7+ to deconstruct object into variables like that:

```cs
var (id, name) = person;

//given
[Record]
class Person { public string Id { get; } public string Name { get; } }
```

Also looking at the example might be more informative (there are links on the main page): https://amis92.github.io/RecordGenerator/examples/Person.html

**Comment by mwpowellhtx** [comment]
Interesting. Okay, thanks for the illustrative example. :+1:
