### ISSUE TITLE
What do you do for deployment concerns?

### ISSUE THREAD

**Issue by mwpowellhtx** [amis92/RecordGenerator#38]
I got my Roslyn code generation bits more or less sorted notwithstanding local testing. Now starting to turn my attention somewhat toward distribution concerns. Man oh man, the Roslyn docs are poor; and that's a generous assessment in my opinion. I found a [halfway decent Roslyn composer](http://roslynquoter.azurewebsites.net/) which takes a snippet of code and spits out some Roslyn code generation code; reading between the lines, one can at least make some informed decisions how better to approach the issue, at any rate. There are perhaps half a dozen sites like that if you happen to ask the right search criteria, I suppose.

Anyway, there is the [VSIX](/amis92/RecordGenerator/tree/master/src/Amadevus.RecordGenerator.Analyzers.Vsix), correct, for purposes of drawing in the [Analyzers](/amis92/RecordGenerator/tree/master/src/Amadevus.RecordGenerator.Analyzers)? I see you also have this published via NuGet, however; is that acceptable in lieu of VSIX? What do you do for the [Attributes](/amis92/RecordGenerator/tree/master/src/Amadevus.RecordGenerator.Attributes) and [Generators](/amis92/RecordGenerator/tree/master/src/Amadevus.RecordGenerator.Generators)?

Actually, I see you have a [parent distribution](/amis92/RecordGenerator/tree/master/src/Amadevus.RecordGenerator) that contains all the dependencies. That pretty much rolls it all up in one bundle, yes? Ostensibly, I assume it rolls up as a [development only dependency](/RecordGenerator/blob/master/src/Amadevus.RecordGenerator.Generators/Amadevus.RecordGenerator.Generators.csproj#L7)?

As such, I'm wondering if I should target both ``.NET Standard 1.x`` (i.e. ``1.6``) and ``2.x`` (i.e. ``2.1``, or whatever it is today).

Thanks!

**Comment by mwpowellhtx** [comment]
I should also ask, how is it you utilize [CodeGeneration.Roslyn.Tasks](/AArnott/CodeGeneration.Roslyn/tree/master/src/CodeGeneration.Roslyn.Tasks)? i.e. [CodeGeneration.Roslyn.BuildTime](https://www.nuget.org/packages/CodeGeneration.Roslyn.BuildTime/)

**Comment by amis92** [comment]
* Analyzer VSIX is mainly for debugging purposes - it's not really possible to debug the analyzer on its own. Debugging VSIX launches new "clean" Visual Studio instance with that VSIX installed. Of course, you could distribute analyzer by VSIX, but it's very different. Analyzers installed via NuGet are per project, and VSIX install makes given Analyzers global for that VS instance.
* Yes, main NuGet package is actually just a bundle of all the other packages, and also yes, it's declared as development dependency.
* If you decide to distribute VSIX, I can't help, I haven't explored that area.
* I'm not sure with what project/package do you want to target both 1.6 and 2.0 of `netstandard`.
* I'm also not sure what is it you ask about CodeGeneration.Roslyn.BuildTime. It's a package required in the project that has the code generated. It's a package that adds appropriate MSBuild Targets which actually run the `CodeGeneration.Roslyn.Tool` (ala `dotnet-codegen`) during build. So when you consume a generator by NuGet, you need to reference both (BuildTime + dotnet-codegen).

For an example of using my RecordGenerator, please take a look here: https://github.com/WarHub/wham/blob/b22182b7ee1fbe09b848454be80e44c0bfad9f3d/src/WarHub.ArmouryModel.ProjectModel/WarHub.ArmouryModel.ProjectModel.csproj

**Comment by mwpowellhtx** [comment]
> Analyzer VSIX is mainly for debugging purposes... If you decide to distribute VSIX, I can't help, I haven't explored that area.

I wasn't considering it, outside of sorting out the bits as a frame of reference. Re: debugging, makes perfect sense, fair enough. But for that matter if it can be distributed via NuGet package reference, then I should think in theory that a project reference would be sufficient?

Re: ``dotnet-codegen``, would that make sense as a bundle dependency then? Or is that not really related, per se? i.e. not that strong of a dependency...

Thanks again for the clarification! :+1:

**Comment by amis92** [comment]
> […] But for that matter if it can be distributed via NuGet package reference, then I should think in theory that a project reference would be sufficient?

Yeah, no. Analyzers are loaded in a special way from NuGet packages, and Project-to-Project references don't work.

`dotnet-codegen` is a `DotNetCliTool` and so must be directly referenced from consuming project. Making it a dependency of your generator won't import it into generator-consuming project.

**Comment by mwpowellhtx** [comment]
@amis92 I came across this [EF LINQ analyzer project](/jumpinjackie/roslyn-ef-linq-analyzer), which seems to have some unit testing comprehension that does not include working through a VSIX session. From the looks of things, they embed source code as a file in an assembly resource, then have Roslyn attempt to compile that file, the diagnostic output from which may or may not include the expected analyzer bits. Thoughts?

**Comment by amis92** [comment]
I can't answer most of your questions, too little context.
* I don't know what doesn't work for you with VSIX debugging. Works for me.
* I don't know exact requirements for Analyzers (netstandard 1.3/1.6).
* [EFLINQ tests] That's cool. Testing is not debugging though. I've got my tests, too. I also do similar things, except I embed the code insinde test files, which may probably be a worse idea.

From the sounds of it, you might be confusing unit tests (which are xUnit-based in case of this repo, and also fire up roslyn and check it's results), with debugging the analyzer, which involves debugging VSIX extension. This is done by Visual Studio by launching a new instance of "temp" clear VS install with that VSIX installed (which means that it has your Analyzer globally installed). Then you can create or open some project, write some code and set breakpoints within the code of your analyzer that get hit when the debug-instance-VS runs background/foreground Build, which in most cases means immediately after you write Analyzer-activating code.

**Comment by mwpowellhtx** [comment]
No, I'm pretty clear, I think. My point there is, if the code is active in any way via an in-memory Roslyn instance, let's say, as in the unit tests, then I should think it would be possible to also debug the same code Roslyn leverages in order to achieve the diagnostic response. At least that's my understanding; I'm working through it at the moment.

As for the VSIX *devenv* instance; yes, I understand all that, such as it is. However, I half expected to see a couple of those breakpoints, and I could even see my extension among the listed extensions, but for whatever reason, I was not finding my analyzer breakpoints. I'll double check I am rolling up the analyzer properly in the VSIX, but I thought I was.

That's when I drudged up the EF tests, and figured, if I can invoke Roslyn directly like that, and embed an analyzer, then I don't need to muck around with VSIX at all.

**Comment by amis92** [comment]
Well, the unit tests here are template-generated (everything except `RecordMustBePartialTests.cs`).

And I can definitely debug my analyzer when debugging unit tests. Roslyn is just an API. Here is the call to make compilation with analyzers: https://github.com/amis92/RecordGenerator/blob/20720be117e8a0ddff8039b4593a6368ab558cab/test/Amadevus.RecordGenerator.Analyzers.Test/Helpers/DiagnosticVerifier.Helper.cs#L60

**Comment by mwpowellhtx** [comment]
Ah, :+1: yes, indeed.

**Comment by mwpowellhtx** [comment]
:+1: I like the idea of keeping all theorized inputs and outputs neatly bundled together; as contrasted with exposure of source inputs via resource inclusion.

**Comment by mwpowellhtx** [comment]
@amis92 I need a little help, couple of clues, which project template? I'm catching wind that perhaps it originated in the *.NET Compiler Platform SDK* (?), i.e. *Roslyn*?

**Comment by amis92** [comment]
Yes, that's the one.

![image](https://user-images.githubusercontent.com/2671396/40691280-6dad4326-63ab-11e8-8038-0e5d47928915.png)

**Comment by amis92** [comment]
The SDK you mentioned installs the templates shown above.

**Comment by mwpowellhtx** [comment]
Oh okay, yes. I just realized this today.

**Comment by mwpowellhtx** [comment]
Perhaps I am missing something... There are a handful of metadata references appended to the ad-hoc workspace Solution Project, but I do not see any of the Record Generator stuff added. Are those carried along with the project itself?

**Comment by amis92** [comment]
The generated stuff is visible from VS class tree view within Solution Explorer:

![image](https://user-images.githubusercontent.com/2671396/40828488-0fe95d92-6581-11e8-94f2-4130506f36d8.png)

Here, when you double click on one of the generated members, it'll open read-only generated file from /obj folder. These files are generated on every build, and so do not persist in VCSs (git/tfs).

**Comment by mwpowellhtx** [comment]
Thanks for all the feedback. I think I got it more or less sorted. It seems like order matters, so I added the references from the base class first, followed by those that are application specific, then the Roslyn compilation verification worked.
