### ISSUE TITLE
Q: How to test Generators...

### ISSUE THREAD

**Issue by mwpowellhtx** [amis92/RecordGenerator#40]
Hello again, and sorry for the question. Not sure how else to inquire...

How do you unit test your Roslyn Generators? With the understanding, of course, the stuff you are generating would be different than the stuff I want to generate.

Intuitively, it seems to me like, assuming I reference my Generators assembly from my unit test assembly, then connect the Attribute, etc, I should see the results of the generated bits in the resulting assembly image, that I could potentially use reflection, etc, in order to verify the results?

Thank you for any insights you can share!

**Comment by amis92** [comment]
I suggest we take discussion onto gitter, it's more of a chat and won't take up issues here :)

https://gitter.im/amis92/RecordGenerator
