### ISSUE TITLE
Configuration in record attribute

### ISSUE THREAD

**Issue by amis92** [amis92/RecordGenerator#45]
A Flags enumeration that by default contains some options.

Also assembly-level attribute support that configures defaults for all records in a given assembly.

**Comment by amis92** [comment]
Regarding parametrizing the `RecordAttribute`, I think the best way forward would be to use a `[Flags]` enum that'll switch on/off various features.

I'd imagine something like that:

```cs
public sealed class RecordAttribute : Attribute
{
    public RecordAttribute()
    {

    }

    public RecordAttribute(Parts parts)
    {
        Parts = parts;
    }

    public Parts Parts { get; } = Parts.Common;
}

[Flags]
public enum Parts
{
    None = 0,
    Constructor = 0b1,
    Withers = 0b10,
    Builder = 0b100,
    Deconstructor = 0b1000,
    Common = Constructor | Withers | Builder | Deconstructor,

    Equals = 0b10000,
    EqualityOperator = 0b100000,
    GetHashCode = 0b1000000,
    Equality = Equals | EqualityOperator | GetHashCode
}
```

What do you think?

_Originally posted by @amis92 in https://github.com/amis92/RecordGenerator/pull/56#issuecomment-514554900_

**Comment by amis92** [comment]
> Regarding parametrizing the `RecordAttribute`, I think the best way forward would be to use a `[Flags]` enum that'll switch on/off various features.

:+1:

> I'd imagine something like that:
>
> ```cs
> [Flags]
> public enum Parts
> {
>     None = 0,
>     Constructor = 0b1,
>     Withers = 0b10,
>     Builder = 0b100,
>     Deconstructor = 0b1000,
>     Common = Constructor | Withers | Builder | Deconstructor,
> 
>     Equals = 0b10000,
>     EqualityOperator = 0b100000,
>     GetHashCode = 0b1000000,
>     Equality = Equals | EqualityOperator | GetHashCode
> }
> ```

I would call it `Features` or `Options` rather than `Parts` because _parts_ is confusing with _partial_. If `Features`/`Options` is too esoteric then `RecordImplementation` would be equally good and explicit.

Nice idea with `Common` but I would just have `Constructor` and `Withers` (which I'd like to suggest renaming to simply `With` although I am all up for creative names) in there unless you would consider adding `Minimal = Constructor | Withers`.

In C#, a `~` member is really called a [_finalizer_][dtor] but [the documentation][dtor] does say that they are also called deconstructors:

> Finalizers (which are also called **destructors**) are used to perform any necessary final clean-up when a class instance is being collected by the garbage collector.

Consequently, I would rename `Deconstructor` to `Deconstruct`.

[dtor]: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors

The equality members (`Equals` and `GetHashCode`) have to work in tandem so I wouldn't give the option to have one implemented and not the other.

I would also recommend inverting some of the flags as an overall design. You want the generator to produce the most sensible and commonly expected features (albeit opinionated?) of a record and opting out some and opting in other nice-to-haves or esoteric cases. In short, I'm thinking this:

```
[Flags]
public enum Features
{
    Basic = 0, // all !excluded + !included
    
    // opt-out
    
    ExcludeConstructor      = 0b0001,
    ExcludeWithers          = 0b0010,
    ExcludeEquality         = 0b0100,
    ExcludeEqualityOperator = 0b1000,
    
    // opt-in

    IncludeBuilder          = 0b0001_0000,
    IncludeDeconstruct      = 0b0010_0000,
    IncludeUpdate           = 0b0100_0000,
}
```

As an aside, shouldn't this design be discussed and iterated in a separate issue as opposed to as part of this PR?

_Originally posted by @atifaziz in https://github.com/amis92/RecordGenerator/pull/56#issuecomment-514568164_

**Comment by amis92** [comment]
`Features` are all right.

I'd definitely not want to do Exclude/Include. `Basic` instead of `Common` is ok, but I want to stay with "byte per feature" approach, keep `None` mostly for zero-is-nothing policy.

**Comment by amis92** [comment]
> Nice idea with Common but I would just have Constructor and Withers (which I'd like to suggest renaming to simply With although I am all up for creative names) in there unless you would consider adding Minimal = Constructor | Withers.

I think Deconstruct is indeed too much for Basic/Common scenario, and Builder is on the fence, I'm not strongly for it being in there, though from *my* usage, it's almost always used (I like the initializer syntax). Still, can be dropped from Basic.

> In C#, a ~ member is really called a finalizer but the documentation does say that they are also called deconstructors:
> 
> Finalizers (which are also called destructors) are used to perform any necessary final clean-up when a class instance is being collected by the garbage collector.
> 
> Consequently, I would rename Deconstructor to Deconstruct.


`~Finalizer` => destructor, `Deconstruct` => deconstructor. They're different, and deconstructor is actually very good name because it's essentially de-constructor (ctor takes group of values, returns object, dector takes object, returns group of values). Still, using actual generated members name might be ok. (e.g. With/Deconstruct)

> The equality members (Equals and GetHashCode) have to work in tandem so I wouldn't give the option to have one implemented and not the other.

Good point. Agreed.

**Comment by jflepp** [comment]
I agree with @amis92 to not introduce the enable / disable enum approach.

Would it be a good idea to introduce a `All` flag? Could look somehow like this: `All = Common | Equality`

While I see the bitwise flags approach sufficent, I would suggest that we could also use `params` Flag arrays. 

~~~~ cs
public sealed class RecordAttribute : Attribute
{
    public Feature[] Features { get; }

    public RecordAttribute(params Feature[] features)
    {
        Features = features;
    }
}

public enum Feature
{
    Constructor,
    Builder,
}

[Record(Feature.Builder, Feature.Constructor)]
public partial class Container
{
}
~~~~

I find the params array approach more intuitive.

**Comment by atifaziz** [comment]
> `~Finalizer` => destructor, `Deconstruct` => deconstructor. They're different, …

Sorry, my bad. I misread _destructors_ as _deconstructor_ in the docs, but anyway, destructuring and deconstructing are overloaded in our industry. We should use the same terminology and vocabulary as the C# docs where possible. The fact that `Deconstructor` threw me off personally is inconsequential and I can live with it.

> I'd definitely not want to do Exclude/Include. `Basic` instead of `Common` is ok, but I want to stay with "byte per feature" approach, …

You didn't give any rationale for the "byte per feature" (did you mean _bit_?) and how it plays better.

> …keep `None` mostly for zero-is-nothing policy

Just curious how's that different than removing or commenting out the attribute?

I guess every user can implement their policy and I wanted a single place to be able to do that for all records in my project. I can implement the baisc + opt-in + opt-out model on top of "byte per feature" like this:

```c#
static class RecordFeatures
{
    public const Features Basic = Features.Constructor
                                | Features.Withers
                                | Features.Equality;

    // opt-in

    public const Features IncludeBuilder          = Features.Builder;
    public const Features IncludeDeconstruct      = Features.Deconstructor;
    
    // opt-out
    
    public const Features ExcludeConstructor      = ~Features.Constructor;
    public const Features ExcludeWithers          = ~Features.Withers;
    public const Features ExcludeEquality         = ~Features.Equality;
    public const Features ExcludeEqualityOperator = ~Features.EqualityOperator;
}

[Record(RecordFeatures.Basic & RecordFeatures.ExcludeEquality
                             & RecordFeatures.ExcludeWithers
                             | RecordFeatures.IncludeBuilder)]
partial class Foo {}
```

It's just not ideal because I have to be extremely careful to do exclusions first and then inclusions (`&` having a higher precedence than `|`), and also make sure that I use `&` with exclusions and `|` with inclusions. As you can imagine, lots of room for errors.

**Comment by amis92** [comment]
@atifaziz re: single place form all records in a project. From OP:

> Also assembly-level attribute support that configures defaults for all records in a given assembly.

That's a feature I'd not release flags without.

**Comment by amis92** [comment]
The `enum` has the advantage of being easily readable from within the generator. You just do the `AttributeData.CtorArgs[0].Value` or similar, writing from memory. Also @jflepp that's why `params` *could* work, but would require additional implementation for handling.

In terms of the Include/Exclude vs bit-flags, I'd say that include/exclude is less intuitive than simply listing features you want. Common/All positions are just for convenience so if you want them, you don't have to write out all of their parts. If you want some custom configuration, you have to specify every single one. That's the "common-> easy, custom->harder" approach I expect us to provide.

**Comment by amis92** [comment]
My proposal:

* `Basic`: Ctor+With
* `Common`: Ctor+With+Builder+Equality

`Common` is the default when nothing is specified.

`All` could just be `int.MinValue`, I'm ok with that.

**Comment by atifaziz** [comment]
> > Also assembly-level attribute support that configures defaults for all records in a given assembly.
> 
> That's a feature I'd not release flags without.

That's awesome. The consts-of-features based approach enables logical and project-level record schemes, which is where I am gravitating, so while the assembly-level attribute would help define the basic features across all records, I would then shoot for:

```c#
static class RecordFeatures
{
    public const Features Basic = Features.Constructor
                                | Features.Withers
                                | Features.Equality;

    public const Features Internal = Basic;
    public const Features Public   = Basic | Features.Builder;
}

[Record(RecordFeatures.Public)]
partial class Foo {}

[Record(RecordFeatures.Internal)]
partial class Bar {}
```

This is a manageability thing and it works whether you slice it as include/exclude or bit-flags.
