### ISSUE TITLE
Validate - pass parameters by value instead of ref

### ISSUE THREAD

**Issue by amis92** [amis92/RecordGenerator#54]
It's a (little but some anyway) overhead for reference types which are rather most of cases.

Also, Validate should probably not allow changing the actual values in constructor which it currently does.

**Comment by atifaziz** [comment]
What do you think about validating post-initialization? For example:

```c#
partial class ValidatingRecord
{
    public ValidatingRecord(string name, string @switch)
    {
        this.Name = name;
        this.Switch = @switch;
        Validate();
    }

    partial void Validate();
}
```

The two downsides I see are:

1. All fields get initialised and therefore work is wasted if an argument isn't valid.
2. You cannot change the values.

I don't think point 1 is so bad because work is currently being wasted anyway pushing all arguments on the stack so is that any different then?

As for downside 2, you wanted that anyway:

> Validate should probably not allow changing the actual values in constructor which it currently does

I think this is fair but if someone wants some magic or defaulting, they should probably introduce factory methods and then making the constructor private becomes another discussion.

**Comment by amis92** [comment]
Argument name is indeed lost, as you've noticed in the PR.

I'd focus on how we'd like to allow the constructor to be extended. After we agree on that we can make Validate behave accordingly.

**Comment by atifaziz** [comment]
One _big_ downside of having a single & central validation method is that every with-member that updates a copy will end up validating everything, which can be wasteful for a large record!

**Comment by amis92** [comment]
That's true, but we cannot have public constructor and optimize that away at the same time.

**Comment by atifaziz** [comment]
> I'd focus on how we'd like to allow the constructor to be extended.

Sorry but what's the idea behind that? What kind of extensions are you thinking of?

**Comment by amis92** [comment]
> I'd focus on how we'd like to allow the constructor to be extended.
> 
> Sorry but what's the idea behind that? What kind of extensions are you thinking of?

Well, since the constructor is auto-generated, the user can't add any single statement. The Validate method is at the same time an extension point that promises to always run as part of the constructor, with the same arguments.

**Comment by amis92** [comment]
> One big downside of having a single & central validation method is that every with-member that updates a copy will end up validating everything, which can be wasteful for a large record!

I'd like to see how you'd solve that (decentralized validation running only on updated values).

**Comment by atifaziz** [comment]
Constructor extension seems to be a different topic whereas I thought this is about validation purely. After all, the method is called `Validate` and not `OnConstructed`.

That aside, I think if you want construction intelligence and customisation then you need to allow factory methods that can then validate arguments, do defaulting and what not and then invoke the constructor _internally_ with only valid state (which implies a new feature like `Features.InternalConstructor`).

(thinking out loud)

**Comment by amis92** [comment]
For a moment I thought about doing validation per-property:

```csharp
static partial void ValidateName(string name);

static partial void ValidateName(string name) => name ?? throw new ArgumentNullException(nameof(name));
```

This'd only pass around arguments that are validated, decreasing the value-copying costs.

But still we couldn't stop running this in constructor even if we invoked it in WithName, because constructor has to run anyway.

**Comment by atifaziz** [comment]
> I'd like to see how you'd solve that (decentralized validation running only on updated values).

The only way I can imagine this right now is to have an `enum` of flags for the record members and then flag those being updated. The with-methods will set the individual flag and the constructor/factory will set them all. The validation method will then validate those properties that are flagged as having been modified. Accidental or incidental complexity? 🤔

**Comment by amis92** [comment]
That is interesting. Worth keeping in mind, but definitely out of scope for our current MVP.

**Comment by atifaziz** [comment]
> out of scope for our current MVP

Do we have the MVP defined somewhere? 😄 

If it affects the public/internal design of records then I imagine this is something you want to get right from the start. If we implement internal constructors then I agree that we should drop validation entirely for the MVP and bring it back after some field use. Thing is, you can go wrong with validation by either under- or over-engineering but there's nothing that can go wrong with an internal constructors and so I would consider as essential to the MVP.

**Comment by amis92** [comment]
Okay. Please, describe what *internal constructors* would look like?

**Comment by amis92** [comment]
After reading above comment, I'll drill down in the question: what would the design of making internal constructors involve? Just `internal` modifier? Factory methods? What would change in other generated members? etc.

**Comment by amis92** [comment]
As stated in the PR #83, I think your proposed, simplified approach of parameterless instance `Validate` method is good-enough.

**Comment by atifaziz** [comment]
Thanks for the merging #83! I guess ea57abfaca554d24a7d2a7c77030ad7773562326 closes this?
