### ISSUE TITLE
Use camelCase instead of PascalCase parameter names

### ISSUE THREAD

**Issue by atifaziz** [amis92/RecordGenerator#57]
The naming convention in .NET for parameters is to use camel case (`fooBar`) but the generator uses Pascal case (`FooBar`) like properties do.

I'd be happy to submit a PR to fix this if it would be welcome.

**Comment by amis92** [comment]
Well, yeah. A PR will be welcome, definitely. I'd like to keep it super-simple, so lower-casing the first character.


Also, this PR will need as a pre-requisite the #28. Can you do that as well?

**Comment by atifaziz** [comment]
> Also, this PR will need as a pre-requisite the #28. Can you do that as well?

I'm afraid I am not familiar with analyzers so it might take me more time. I can try but otherwise should this stall until #28 is done? Or can I still submit a PR for this and you merge once #28 is done? Thinking how we can avoid a waterfall approach here.

**Comment by amis92** [comment]
Sure, go on with this, and I'll add the analyzer to your PR maybe, so remember to check "allow contributor to make changes" or something when opening PR.

**Comment by amis92** [comment]
Although feel free to try the Analyzers yourself, it's not so hard and quite fun :D

**Comment by atifaziz** [comment]
> Although feel free to try the Analyzers yourself, it's not so hard and quite fun :D

Sounds like a great opporunity to do this together using [VS Live Share](https://visualstudio.microsoft.com/services/live-share/) if it's not hard and it would certainly be a fun experience. 😉

**Comment by amis92** [comment]
That'd be great! Do you use gitter or other platform with PMs so we can agree on timeframe and other details?

**Comment by atifaziz** [comment]
> That'd be great!

Awesome!

> Do you use gitter…

Yes, I do!
